### PR TITLE
consolidate maven, karaf, osgi configuration

### PR DESCRIPTION
**Pull request by acoburn**
This simplifies your maven configuration by creating a single parent POM from which other components inherit. It also consolidates your karaf features files into a single one (adding a `repositories` and `configfile` section for each feature to make provisioning more fun).

This also updates the version of `Aries` used in your blueprint files to make is possible to hot-deploy configuration changes in karaf (meaning: you modify a config file and the appropriate routes automatically redeploy).

And rather than consolidating configuration into a single file, this separates the configuration by service, and automatically pushes each configuration file (`./src/main/cfg/*.cfg`) into `$KARAF_HOME/etc` when deploying (AFAIK, you can't have auto-redeploy work when there is a single, shared config file -- though I could be wrong there).

Finally, this sets default configuration values in the blueprint files, so that in the event that a `*.cfg` file doesn't contain the requested property, the value defaults to what is defined in the `blueprint.xml` file.

N.B. I didn't know there was a `camel-mustache` component: I'm going to start using that RIGHT NOW!

### CODE REVIEW

**Comment by daniel-dgi** [comment]
Niiiiiiiiiiiice.  Pulling in changesets and spinning up a vm.

**Comment by acoburn** [comment]
@daniel-dgi I called the parent POM `islandora-parent`. Not sure if you'd prefer it to be simply `islandora`

**Comment by acoburn** [comment]
... or `islandora-camel`

**Comment by daniel-dgi** [comment]
Thx for the extra eyes.  I have serious issues doing rebuilds at home.  Maybe make new ticket for basebox?

Anyhow, merged.

**Pull request merged**
